# Generated by Django 4.1.4 on 2022-12-10 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=1000)),
                ('Password', models.CharField(max_length=100)),
                ('Created_By', models.CharField(max_length=100)),
                ('Created_dttm', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=1000000000)),
                ('Delivered_dttm', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('User', models.CharField(max_length=100)),
                ('room_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ChatRoomApp.room_details')),
            ],
        ),
    ]
