# Generated by Django 4.1.4 on 2022-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoomApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_details',
            name='room_id',
        ),
        migrations.AddField(
            model_name='message_details',
            name='room_name',
            field=models.CharField(default='NULL', max_length=1000),
        ),
    ]
